### ISSUE TITLE
VirtualTourXR (Editor): Does not seem to work well when run as subcontent

### ISSUE THREAD

**Issue by patrickfrohmann** [codefluegel/h5p-virtual-3D-tour#4] opened 2024-11-14 14:20 UTC
When edited as subcontent, the editor widget does not create a scene from the image that is used and crashes if one tries to add something onto the empty scene.

**Comment by patrickfrohmann** [comment] 2024-11-14 14:21
![Image](https://github.com/user-attachments/assets/aa310b85-c2b6-40f2-af1d-b9cceb536d47)


params are not correctly passed from column type... i think this needs further investigation

**Comment by patrickfrohmann** [comment] 2024-11-14 15:17
@otacke any hint how to adapt? i guess column type?

**Comment by otacke** [comment] 2024-11-14 16:12
This needs further investigation, yes. I highly doubt that Column is responsible. It's likely that this is some issue in the editor widget of the EscapeRoom original or even in the VirtualTour original that EscapeRoom was derived from.

**Comment by otacke** [comment] 2024-11-29 10:52
The cause is a bug in the original Virtual Tour implementation that implicitly assumes that the parent instance is the main editor form which does not provide `params` the way that an editor library widget does - the latter is what we deal with when the content is run as subcontent.

Fixed in https://github.com/codefluegel/h5p-editor-virtual-tour-xr/pull/1

**Closed as completed** 2024-11-29 12:57 UTC
